- id: shellcheck
  name: shellcheck
  description: Test shell scripts with shellcheck
  entry: shellcheck
  language: python
  types: [shell]
  require_serial: true # shellcheck can detect sourcing this way
