name: main

on:
  push:
    branches: [main, test-me-*]
    tags: '*'
  pull_request:

jobs:
  main-windows:
    uses: asottile/workflows/.github/workflows/tox.yml@v1.11.1
    with:
      env: '["py311"]'
      os: windows-latest
      wheel-tags: true
  main-macos:
    uses: asottile/workflows/.github/workflows/tox.yml@v1.11.1
    with:
      env: '["py311"]'
      os: macos-latest
      wheel-tags: true
  main-macos-intel:
    uses: asottile/workflows/.github/workflows/tox.yml@v1.11.1
    with:
      env: '["py311"]'
      os: macos-15-intel
      wheel-tags: true
  main-linux:
    uses: asottile/workflows/.github/workflows/tox.yml@v1.11.1
    with:
      env: '["py311"]'
      os: ubuntu-latest
